#!/bin/bash -e

. /usr/share/debconf/confmodule
db_input high atlas-server/vpn-dns || true
db_input high atlas-server/nginx || true
db_go
db_get atlas-server/vpn-dns
export VPN_DNS=$RET
db_get atlas-server/nginx
if [[ $RET = true ]]; then
	db_input high atlas-server/backend-port || true
	db_input high atlas-server/stream-port || true
	db_input high atlas-server/external-port || true
	db_input high atlas-server/server-name || true
	db_input high atlas-server/cert-dir || true
	db_go
fi
db_get atlas-server/backend-port
export BACKEND_PORT=$RET
db_get atlas-server/stream-port
export STREAM_PORT=$RET
db_get atlas-server/external-port
export EXTERNAL_PORT=$RET
db_get atlas-server/server-name
export SERVER_NAME=$RET
db_get atlas-server/cert-dir
export CERT_DIR=$RET
set -x

systemctl daemon-reload
systemctl enable postgresql
systemctl start postgresql

id atlas || useradd -Mrs/sbin/nologin -d/ atlas
id atlas-streamer || useradd -Mrs/sbin/nologin -d/ atlas-streamer
su -s/bin/sh postgres -c "createuser -d atlas" || true

su -s/bin/sh atlas -- -ex << EOF
createdb atlas || true
psql -c "ALTER USER atlas PASSWORD 'atlas';"

. /etc/atlas.env
export DATABASE_URL
/usr/lib/atlas/sqlx migrate run --source=/usr/share/atlas/migrations
EOF

sed -i "s/1400/$BACKEND_PORT/" /etc/atlas.env
sed -i "s/1401/$STREAM_PORT/" /etc/atlas.env

cp /usr/share/atlas/nginx.conf.template /etc/nginx/sites-enabled/atlas
if [[ ! $CERT_DIR ]]; then
	sed -i -e '/ssl_/ s/\w/# \0/' -e 's/ http2 ssl//' /etc/nginx/sites-enabled/atlas
fi
envsubst < /etc/nginx/sites-enabled/atlas > /tmp/nginx.conf
mv /tmp/nginx.conf /etc/nginx/sites-enabled/atlas
if pidof nginx; then systemctl reload nginx || echo Failed to reload nginx; fi

if pidof tmdbd; then systemctl restart atlas-server tmdbd; fi

if [[ $VPN_DNS ]]; then
	cat > /etc/systemd/network/10-atlas-streamer.network << EOF
[Match]
Name=tun0

[Network]
DNS=$VPN_DNS
DNSDefaultRoute=yes
EOF

	systemctl restart systemd-resolved
	if systemctl start atlas-vpn atlas-vpn-config atlas-backend atlas-stream; then
		systemctl enable atlas-vpn atlas-vpn-config atlas-backend atlas-stream
	fi
else
	if systemctl start atlas-server-no-vpn; then
		systemctl enable atlas-server-no-vpn
	fi
fi

if systemctl start tor tmdbd; then
	systemctl enable tor tmdbd
fi
