[package]
name = "overlay"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.9"
gtk = { version = "0.4", package = "gtk4" }
relm4 = "0.4"
relm4-components = "0.4"
relm4-macros = "0.4"
