name: atlas
version: 0.0.0
summary: Atlas client
description: Atlas client
confinement: strict
compression: lzo
grade: stable
base: core22

apps:
  frontend:
    daemon: simple
    restart-condition: always
    restart-delay: 1s
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/wayland-launch
    command: bin/wrapper
    plugs:
      - alsa
      - network
      - network-bind
      - network-manager
      - opengl
      - process-control
      - wayland

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

environment:
  # graphics
  LD_LIBRARY_PATH: $SNAP/graphics/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/samba:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/lapack${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  LIBVA_DRIVERS_PATH: $SNAP/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d
  # XDG
  XDG_CACHE_HOME: $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_DATA_HOME: $SNAP_USER_DATA
  XDG_DATA_DIRS: $SNAP/usr/local/share:$SNAP/usr/share
  # GTK
  GDK_GL: gles
  GTK_A11Y: none
  GTK_USE_PORTAL: 0
  # other
  PYTHONPATH: $PYTHONPATH:$SNAP/usr/lib/python3/dist-packages
  RUST_BACKTRACE: 1
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb

parts:
  frontend:
    plugin: nil
    source: frontend
    build-snaps:
      - flutter/latest/stable
    build-environment:
      - C_INCLUDE_PATH: /snap/flutter/current/usr/include
      - LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/snap/flutter/current/usr/lib/$CRAFT_ARCH_TRIPLET
      - PKG_CONFIG_PATH: ${PKG_CONFIG_PATH:+$PKG_CONFIG_PATH:}/snap/flutter/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
      - XDG_DATA_DIRS: /snap/flutter/current/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/bin/lib
      if [[ ! -d ~/snap/flutter/common/flutter ]]; then
        flutter channel stable
        flutter upgrade
      fi
      pushd ~/snap/flutter/common/flutter
      git checkout 3.13.9
      popd
      flutter config --enable-linux-desktop
      flutter doctor
      flutter pub get
      flutter build linux --dart-define=ATLAS_VERSION=$SNAPCRAFT_PROJECT_VERSION --release -v
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    stage-packages:
      - libgtk-3-0
      - libgl1

  overlay:
    plugin: rust
    source: overlay
    build-packages:
      - cargo
      - libgtk-4-dev
      - libssl-dev
      - libudev-dev
      - pkg-config
      - rustc
    stage-packages:
      - psmisc
    stage:
      - bin/atlas-overlay
      - usr/bin/killall

  deps:
    plugin: nil
    stage-packages:
      - libasound2
      - libgtk-4-1
      - mpv
      - network-manager
      - ubuntu-restricted-extras
      - yt-dlp

  fonts:
    plugin: nil
    stage-packages:
      - fonts-cantarell
      - fonts-noto
      - fonts-noto-cjk
      - fonts-noto-extra
    stage:
      - usr/share/fonts/opentype/cantarell
      - usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc
      - usr/share/fonts/truetype/noto/NotoSansMono-*.ttf

  dotenv:
    plugin: dump
    source: env
    organize:
      client.env: .env
    stage:
      - .env

  wrapper:
    plugin: dump
    source: wrapper
    organize:
      wrapper.sh: bin/wrapper

  version:
    plugin: nil
    override-prime: echo $SNAPCRAFT_PROJECT_VERSION > $CRAFT_PRIME/VERSION

  gsettings+pixbuf+immodules:
    plugin: nil
    build-packages:
      - libgdk-pixbuf2.0-0
      - librsvg2-common
      - shared-mime-info
      - libgtk-3-0
    override-build: |
      craftctl default
      # Update mime database
      update-mime-database ${CRAFT_PART_INSTALL}/usr/share/mime
      # build immodules cache
      mkdir -p ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0/3.0.0/
      /usr/lib/${CRAFT_ARCH_TRIPLET}/libgtk-3-0/gtk-query-immodules-3.0 > ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0/3.0.0/immodules.cache
    stage-packages:
      - librsvg2-common
      - gsettings-desktop-schemas
      - libglib2.0-bin
    override-prime: |
      craftctl default
      # Compile the gsettings schemas
      /usr/lib/${CRAFT_ARCH_TRIPLET}/glib-2.0/glib-compile-schemas "$CRAFT_PRIME/usr/share/glib-2.0/schemas"
      # Index the pixbuf loaders
      LOADERS_PATH=$(echo ${CRAFT_PRIME}/usr/lib/${CRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/*/loaders)
      QUERY_LOADERS=/usr/lib/${CRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
      GDK_PIXBUF_MODULEDIR=${LOADERS_PATH} ${QUERY_LOADERS} > ${LOADERS_PATH}/../loaders.cache
      sed s!$CRAFT_PRIME!!g --in-place ${LOADERS_PATH}/../loaders.cache

  setup:
    plugin: dump
    source: wayland-launch
    override-build: |
      # The plugs needed to run Wayland. (wayland-launch checks them, setup.sh connects them)
      # You may add further plugs here if you want these options
      PLUGS="opengl wayland graphics-core22"
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/wayland-launch
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/setup.sh
      craftctl default
    stage-packages:
      - inotify-tools

  graphics-core22:
    after:
      - frontend
      - overlay
      - gsettings+pixbuf+immodules
      - setup
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
      cd "$CRAFT_PRIME/usr/share/"
      rm -rf bug drirc.d glvnd libdrm lintian man
      rm -rf applications apport bash-completion dbus-1 doc-base doc gtk-doc\
             help pkgconfig libthai metainfo themes thumbnailers xml
    prime:
      - bin/graphics-core22-wrapper

layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0
  /usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0:
    bind: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0
  /usr/share/mime:
    bind: $SNAP/usr/share/mime
  /etc/gtk-3.0:
    bind: $SNAP/etc/gtk-3.0
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

architectures:
  - build-on: amd64
  - build-on: arm64
